export default {
  appName: 'My Shop',
  topcategories: 'Top Categories',
  viewall: 'View all',
  newproducts: 'New Products',
  new: 'New',
  outofstocks: 'Out of stocks',
  forgotPassword: 'Forgot Password',
  login: 'Login',
  signup: 'Sign Up',
  phone: 'Phone',
  search: 'Search',
  editProfile: 'Edit Profile',
  myOrders: 'My Orders',
  logout: 'Logout',
  manageAddress: 'Manage Address',
  changePassword: 'Change Password',
  addToCart: 'Add To Cart',

  Critical: 'Critical',
  High: 'High',
  Medium: 'Medium',
  Low: 'Low',
  // Notification: 'Notification',
  // orderTotal: 'Order Total',
  // orderNo: 'Order No.',
  // deliveryDate: 'Delivery date',
  // paymentMethod: 'Payment Method',
  // revenueOverTime: 'REVENUE OVER TIME',
  // yearly: 'YEARLY',
  // channels: 'All Channels',
  // callToAction: 'Call to Action',
  // TODAYS: "Today's",
  // YESTERDAYS: "Yesterday's",
  // YTD: 'Ytd',
  // ALL: 'All',
  // SNOOZED: 'Snoozed',
  // ACTIVE: 'Active',
  // ORDERS: 'ORDERS',
  // DISMISSED: 'Dismissed',
  // ORDERVALUE: 'ORDER VALUE',
  // revenueFilterTitle: 'Select duration for Revenue over time',
  // slaFilterTitle: 'Select duration for SLA Metric Achievement over time',
  // channelRevenueTitle: 'Select channel for Revenue over time',
  // channelSLATitle: 'Select channel for SLA Metric Achievement over time',
  // Monthly: 'Monthly',
  // Yearly: 'Yearly',
  // infoDialogueTitle: 'Revenue Over Time',
  // topSellingDialogTitle: 'Top Selling Product',
  // topSellingDialogContent:
  //   'The list of top selling products across the channels in the last 3 months . List also shows stock sold, stock left, and shows the amount of days of stock left, based on the rate of sale of the last three months.',
  // infoDialogueContent:
  //   'This chart shows revenue as total value of Orders Shipped - Returned for the period. Yearly option shows the revenue from Jan to Dec of current year as compare to last year on month on month basic. Monthly option shows last 12 months rolling sales revenue.',
  // dialogueOkButton: 'OK',
  // slaMetricDialogueTitle: 'SLA Achievement over time',
  // slaDialogueContent:
  //   'If the order is shipped within the promised shipped time it is considered as SLA achieved . This chart shows SLA achievement over time. Monthly option shows last 12 months rolling SLA data while Yearly shows Year on Year SLA data channel wise.',
  // SLA_METRIC_ACHIEVEMENT_OVER_TIME: 'SLA METRIC ACHIEVEMENT OVER TIME',
  // orderStatus: 'Order Status',
  // ORDERSTATUS: 'ORDER STATUS',
  // orderStatusInfoContent:
  //   'This chart shows break up of Open orders excluding shipped and delivered orders.',
  // totalOrders: 'Total Orders',
  // noDataFound: 'No data found',
  // ProductInformation: 'Product Information',
  // CHANNELWISE_SALES: 'CHANNELWISE SALES',
  // TOP_SELLING_PRODUCT: 'TOP SELLING PRODUCTS',
  // sinceYesterday: 'Since Yesterday',
  // infoChannelWiseSales: 'Channelwise sales',
  // infoChannelWiseContent:
  //   'Channel wise today’s order value with % difference as compare to yesterday and it also shows number of active products on the channel.',
  // SOLD: 'Sold',
  // LEFT: 'Left',
  // DAYS_LEFT: 'Days of Stock Left',

  // INVENTORY_VALUE: 'INVENTORY VALUE',
  // infoInventoryValue: 'Inventory Value',
  // infoInventoryContent:
  //   'This chart shows aggregate Inventory value of the products at Product Category level and shows top 10 categories by the value. Inventory Value = ATP Stock Qty i.e. on hand stock removing all order allocation and reservation X Sales Price as defined in Product Master.',
  // passMisMatch: 'New password and confirm password does not  match',
  // passPerfect: 'Perfect',
  // passWeak: 'Too Weak',
  // passStrength: 'Password Strength',
  // resetPass: 'RESET PASSWORD',
  // backToLogin: 'Back to Login',
  // upperCase: ' One uppercase letter required',
  // lowerCase: 'One lowercase letter required',
  // specialCharacters: 'One special character required',
  // number: 'One Number is required',
  // eightLetters: ' At least 8 characters required',
  // jailbreakHeader: 'JAILBREAK DETECTED',
  // jailbreakContent:
  //   'This app is not supported on jailbroken devices. Please restore your device to a non-jailbroken state',
};
