// Colors palette source https://flatuicolors.com/palette/defo

const ASBESTOS = '#7f8c8d';
const SILVER = '#bdc3c7';

const DARK_TOP_HEADER = '#000000EB';
const LIGHT_TOP_HEADER = '#F5F5F5';
const DARK_TOP_HEADER_TEXT = '#fff';
const LIGHT_TOP_HEADER_TEXT = '#000';

const WHITE = '#FFFFFF';
const BLACK = '#000000';
const DARK_TEXT = WHITE;
const LIGHT_TEXT = '#000';
const RED = '#FF6969';

const LIGHT_BACKGROUND = '#FDFDFD';
const DARK_BACKGROUND = '#000000';
const LIGHT_TEXTINPUT_BACKGROUND = '#EDEDEF';
const DARK_TEXTINPUT_BACKGROUND = '#212121';
const LIGHT_PLACEHOLDER = '#00000066';
const DARK_PLACEHOLDER = '#666666';

const common = {
  PRIMARY: '#5856D6',
  BUTTON: '#5856D6',
  BORDER: '#91919145',
  BUTTON_DANGER: RED,
  TEXT_SUCCESS: '#00D842',
  BUTTON_SUCCESS: '#008D31',
  GRAY_ICON: '#8a8a8f',
};

const light = {
  ...common,
  BACKGROUND: LIGHT_BACKGROUND,
  TEXT: LIGHT_TEXT,
  TEXT_SHADE_1: '#00000080',
  TEXT_SECONDARY: ASBESTOS,
  HEADER_COLOR: LIGHT_TOP_HEADER,
  HEADER_TEXT: LIGHT_TOP_HEADER_TEXT,
  TEXTINPUT_BACKGROUND: LIGHT_TEXTINPUT_BACKGROUND,
  PLACEHOLDER: LIGHT_PLACEHOLDER,
  MODALBG: '#00000066',
  OUTLINE: '#5856D6',
  APP_FOOTER_TEXT: '#8A8A8F99',
  APP_FOOTER_BG: '#F0F0F0',
  CHECKBOX_TICK: WHITE,
  CHECKBOX_UNFILLED: 'rgba(0, 0, 0, 0.15)',
  BOTTOM_NAVIGATION_BACKGROUND: '#fafafa',
  INFO_COLOR: '#D3D3D3',
  INPUT_OUTLINE: '#5856D6',
  RIPPLE_SELECT: '#5856D633',
  SUMMARY_HEADING: '#00000080',
  SUMMARY_AMOUNT: BLACK,
  SUMMARY_VIEW_BACKGROUND: '#FAFAFA',
  GENERATE_AMOUNT: '#7D77FF',
  CHECK_PROMOTION_BUTTON_BACKGROUND: '#0473A9',
  INVOICE_AMOUNT_BACKGROUND: '#fafafa',
  WHITE: WHITE,
};

const dark = {
  ...common,
  BACKGROUND: DARK_BACKGROUND,
  TEXT: DARK_TEXT,
  TEXT_SHADE_1: '#FFFFFF80',
  TEXT_SECONDARY: SILVER,
  HEADER_COLOR: DARK_TOP_HEADER,
  HEADER_TEXT: DARK_TOP_HEADER_TEXT,
  TEXTINPUT_BACKGROUND: DARK_TEXTINPUT_BACKGROUND,
  PLACEHOLDER: DARK_PLACEHOLDER,
  MODALBG: '#FFFFFF4d',
  OUTLINE: '#fff',
  APP_FOOTER_TEXT: '#8A8A8F99',
  APP_FOOTER_BG: '#000000',
  CHECKBOX_TICK: 'black',
  CHECKBOX_UNFILLED: 'rgb(74, 74, 74)',
  BOTTOM_NAVIGATION_BACKGROUND: DARK_BACKGROUND,
  INFO_COLOR: '#696969',
  INPUT_OUTLINE: '#5856D6',
  RIPPLE_SELECT: '#5856D633',
  SUMMARY_HEADING: '#FFFFFF80',
  SUMMARY_AMOUNT: WHITE,
  SUMMARY_VIEW_BACKGROUND: '#121212',
  GENERATE_AMOUNT: '#7D77FF',
  CHECK_PROMOTION_BUTTON_BACKGROUND: '#0473A9',
  INVOICE_AMOUNT_BACKGROUND: '#121212',
  WHITE: WHITE,
};

export const colors = {light, dark};
